import 'package:flutter/material.dart';

TextEditingController fullNameCtrl = TextEditingController();
TextEditingController phoneCtrl = TextEditingController();
TextEditingController emailCtrlSignUp = TextEditingController();
TextEditingController passwordCtrlSignUp = TextEditingController();
TextEditingController confirmPasswordCtrl = TextEditingController();
TextEditingController addressCtrl = TextEditingController();
TextEditingController pinController = TextEditingController();
TextEditingController emailCtrl = TextEditingController();
TextEditingController passwordCtrl = TextEditingController();
TextEditingController resetEmailCtrl = TextEditingController();
TextEditingController countryCodeCtrl = TextEditingController();
TextEditingController countrySearchCtrl = TextEditingController();
TextEditingController stateSearchCtrl = TextEditingController();
TextEditingController citySearchCtrl = TextEditingController();

final TextEditingController workHistoryController = TextEditingController();
// final emailCtrl = TextEditingController();
// final passwordCtrl = TextEditingController();
// final fullNameCtrl = TextEditingController();
// final phoneCtrl = TextEditingController();
// final emailCtrlSignUp = TextEditingController();
// final addressCtrl = TextEditingController();
// final passwordCtrlSignUp = TextEditingController();
final countryController = TextEditingController();
final stateController = TextEditingController();
final cityController = TextEditingController();
final zipController = TextEditingController();
final mailingAddressController = TextEditingController();
  // final pinController = TextEditingController();