// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth_flow/data/datasources/local_datasources/auth_user_local_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5131635798235456301),
    name: 'AuthUserLocalEntity',
    lastPropertyId: const obx_int.IdUid(30, 3271705913206409547),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4611869412995201516),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8272780988710511950),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1482861332686892814),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 997857176921112707),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3976464959677611987),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8134907860381373967),
        name: 'countryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 607818520923023036),
        name: 'mailingAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5012892644845956447),
        name: 'role',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2706555786363321275),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5188505656236194826),
        name: 'phoneOtpVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3279684472998237889),
        name: 'emailOtpVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3139177082061344221),
        name: 'agreedToTerms',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3448151157588637092),
        name: 'isTruthfully',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 132889661029488037),
        name: 'approvalStatusByAdmin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 593940584799512486),
        name: 'rejectedReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2148407587997559327),
        name: 'stripeCustomerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 1493272936218018139),
        name: 'stripeAccountId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4361464192518718559),
        name: 'stripePayoutsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 3222730919390221459),
        name: 'stripeTransfersActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3540610438679751168),
        name: 'currentSubscriptionTrialDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2332234854265821318),
        name: 'currentSubscriptionAutoRenew',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 39882207688389351),
        name: 'currentSubscriptionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 4686123977379770666),
        name: 'stripeSubscriptionStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 6140693525709463196),
        name: 'walletId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5796780863751892772),
        name: 'locationName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 1498496296919574464),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5584120390685559358),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 8462199880617792571),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 6233394496800560090),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 3271705913206409547),
        name: 'loginTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'devices',
        srcEntity: 'AuthUserDeviceEntity',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8224409923190584740),
    name: 'AuthUserDeviceEntity',
    lastPropertyId: const obx_int.IdUid(4, 2446156020687410148),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1201763598529109640),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4991843973117758024),
        name: 'deviceToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2587492729026246349),
        name: 'deviceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2446156020687410148),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7489877441751012150),
        relationTarget: 'AuthUserLocalEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8224409923190584740),
    lastIndexId: const obx_int.IdUid(1, 7489877441751012150),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthUserLocalEntity: obx_int.EntityDefinition<AuthUserLocalEntity>(
      model: _entities[0],
      toOneRelations: (AuthUserLocalEntity object) => [],
      toManyRelations: (AuthUserLocalEntity object) => {
        obx_int.RelInfo<AuthUserDeviceEntity>.toOneBacklink(
          4,
          object.id,
          (AuthUserDeviceEntity srcObject) => srcObject.user,
        ): object.devices,
      },
      getId: (AuthUserLocalEntity object) => object.id,
      setId: (AuthUserLocalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthUserLocalEntity object, fb.Builder fbb) {
        final tokenOffset = object.token == null
            ? null
            : fbb.writeString(object.token!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final countryCodeOffset = object.countryCode == null
            ? null
            : fbb.writeString(object.countryCode!);
        final mailingAddressOffset = object.mailingAddress == null
            ? null
            : fbb.writeString(object.mailingAddress!);
        final rejectedReasonOffset = object.rejectedReason == null
            ? null
            : fbb.writeString(object.rejectedReason!);
        final stripeCustomerIdOffset = object.stripeCustomerId == null
            ? null
            : fbb.writeString(object.stripeCustomerId!);
        final stripeAccountIdOffset = object.stripeAccountId == null
            ? null
            : fbb.writeString(object.stripeAccountId!);
        final currentSubscriptionIdOffset = object.currentSubscriptionId == null
            ? null
            : fbb.writeString(object.currentSubscriptionId!);
        final stripeSubscriptionStatusOffset =
            object.stripeSubscriptionStatus == null
            ? null
            : fbb.writeString(object.stripeSubscriptionStatus!);
        final walletIdOffset = object.walletId == null
            ? null
            : fbb.writeString(object.walletId!);
        final locationNameOffset = object.locationName == null
            ? null
            : fbb.writeString(object.locationName!);
        fbb.startTable(31);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tokenOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(4, phoneNumberOffset);
        fbb.addOffset(5, countryCodeOffset);
        fbb.addOffset(6, mailingAddressOffset);
        fbb.addInt64(7, object.role);
        fbb.addInt64(8, object.status);
        fbb.addBool(9, object.phoneOtpVerified);
        fbb.addBool(10, object.emailOtpVerified);
        fbb.addBool(11, object.agreedToTerms);
        fbb.addBool(12, object.isTruthfully);
        fbb.addInt64(13, object.approvalStatusByAdmin);
        fbb.addOffset(14, rejectedReasonOffset);
        fbb.addOffset(15, stripeCustomerIdOffset);
        fbb.addOffset(16, stripeAccountIdOffset);
        fbb.addBool(17, object.stripePayoutsEnabled);
        fbb.addBool(18, object.stripeTransfersActive);
        fbb.addInt64(19, object.currentSubscriptionTrialDays);
        fbb.addInt64(20, object.currentSubscriptionAutoRenew);
        fbb.addOffset(21, currentSubscriptionIdOffset);
        fbb.addOffset(22, stripeSubscriptionStatusOffset);
        fbb.addOffset(23, walletIdOffset);
        fbb.addOffset(24, locationNameOffset);
        fbb.addFloat64(25, object.latitude);
        fbb.addFloat64(26, object.longitude);
        fbb.addInt64(27, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(28, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(29, object.loginTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          58,
        );
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          60,
        );
        final loginTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          62,
        );
        final tokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final countryCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final mailingAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final roleParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final statusParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final phoneOtpVerifiedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final emailOtpVerifiedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final agreedToTermsParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final isTruthfullyParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final approvalStatusByAdminParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 30);
        final rejectedReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final stripeCustomerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final stripeAccountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final stripePayoutsEnabledParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 38);
        final stripeTransfersActiveParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 40);
        final currentSubscriptionTrialDaysParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final currentSubscriptionAutoRenewParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 44);
        final currentSubscriptionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final stripeSubscriptionStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final walletIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final locationNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final loginTimeParam = loginTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(loginTimeValue);
        final object = AuthUserLocalEntity(
          token: tokenParam,
          name: nameParam,
          email: emailParam,
          phoneNumber: phoneNumberParam,
          countryCode: countryCodeParam,
          mailingAddress: mailingAddressParam,
          role: roleParam,
          status: statusParam,
          phoneOtpVerified: phoneOtpVerifiedParam,
          emailOtpVerified: emailOtpVerifiedParam,
          agreedToTerms: agreedToTermsParam,
          isTruthfully: isTruthfullyParam,
          approvalStatusByAdmin: approvalStatusByAdminParam,
          rejectedReason: rejectedReasonParam,
          stripeCustomerId: stripeCustomerIdParam,
          stripeAccountId: stripeAccountIdParam,
          stripePayoutsEnabled: stripePayoutsEnabledParam,
          stripeTransfersActive: stripeTransfersActiveParam,
          currentSubscriptionTrialDays: currentSubscriptionTrialDaysParam,
          currentSubscriptionAutoRenew: currentSubscriptionAutoRenewParam,
          currentSubscriptionId: currentSubscriptionIdParam,
          stripeSubscriptionStatus: stripeSubscriptionStatusParam,
          walletId: walletIdParam,
          locationName: locationNameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          loginTime: loginTimeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<AuthUserLocalEntity>(
          object.devices,
          store,
          obx_int.RelInfo<AuthUserDeviceEntity>.toOneBacklink(
            4,
            object.id,
            (AuthUserDeviceEntity srcObject) => srcObject.user,
          ),
        );
        return object;
      },
    ),
    AuthUserDeviceEntity: obx_int.EntityDefinition<AuthUserDeviceEntity>(
      model: _entities[1],
      toOneRelations: (AuthUserDeviceEntity object) => [object.user],
      toManyRelations: (AuthUserDeviceEntity object) => {},
      getId: (AuthUserDeviceEntity object) => object.id,
      setId: (AuthUserDeviceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthUserDeviceEntity object, fb.Builder fbb) {
        final deviceTokenOffset = object.deviceToken == null
            ? null
            : fbb.writeString(object.deviceToken!);
        final deviceTypeOffset = object.deviceType == null
            ? null
            : fbb.writeString(object.deviceType!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceTokenOffset);
        fbb.addOffset(2, deviceTypeOffset);
        fbb.addInt64(3, object.user.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deviceTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final deviceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = AuthUserDeviceEntity(
          deviceToken: deviceTokenParam,
          deviceType: deviceTypeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthUserLocalEntity] entity fields to define ObjectBox queries.
class AuthUserLocalEntity_ {
  /// See [AuthUserLocalEntity.id].
  static final id = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[0].properties[0],
  );

  /// See [AuthUserLocalEntity.token].
  static final token = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[1],
  );

  /// See [AuthUserLocalEntity.name].
  static final name = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[2],
  );

  /// See [AuthUserLocalEntity.email].
  static final email = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[3],
  );

  /// See [AuthUserLocalEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[4],
  );

  /// See [AuthUserLocalEntity.countryCode].
  static final countryCode = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[5],
  );

  /// See [AuthUserLocalEntity.mailingAddress].
  static final mailingAddress = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[6],
  );

  /// See [AuthUserLocalEntity.role].
  static final role = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[0].properties[7],
  );

  /// See [AuthUserLocalEntity.status].
  static final status = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[0].properties[8],
  );

  /// See [AuthUserLocalEntity.phoneOtpVerified].
  static final phoneOtpVerified = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[0].properties[9],
  );

  /// See [AuthUserLocalEntity.emailOtpVerified].
  static final emailOtpVerified = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[0].properties[10],
  );

  /// See [AuthUserLocalEntity.agreedToTerms].
  static final agreedToTerms = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[0].properties[11],
  );

  /// See [AuthUserLocalEntity.isTruthfully].
  static final isTruthfully = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[0].properties[12],
  );

  /// See [AuthUserLocalEntity.approvalStatusByAdmin].
  static final approvalStatusByAdmin =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[0].properties[13],
      );

  /// See [AuthUserLocalEntity.rejectedReason].
  static final rejectedReason = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[14],
  );

  /// See [AuthUserLocalEntity.stripeCustomerId].
  static final stripeCustomerId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[15],
  );

  /// See [AuthUserLocalEntity.stripeAccountId].
  static final stripeAccountId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[16],
  );

  /// See [AuthUserLocalEntity.stripePayoutsEnabled].
  static final stripePayoutsEnabled =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[0].properties[17],
      );

  /// See [AuthUserLocalEntity.stripeTransfersActive].
  static final stripeTransfersActive =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[0].properties[18],
      );

  /// See [AuthUserLocalEntity.currentSubscriptionTrialDays].
  static final currentSubscriptionTrialDays =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[0].properties[19],
      );

  /// See [AuthUserLocalEntity.currentSubscriptionAutoRenew].
  static final currentSubscriptionAutoRenew =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[0].properties[20],
      );

  /// See [AuthUserLocalEntity.currentSubscriptionId].
  static final currentSubscriptionId =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[0].properties[21]);

  /// See [AuthUserLocalEntity.stripeSubscriptionStatus].
  static final stripeSubscriptionStatus =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[0].properties[22]);

  /// See [AuthUserLocalEntity.walletId].
  static final walletId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[23],
  );

  /// See [AuthUserLocalEntity.locationName].
  static final locationName = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[0].properties[24],
  );

  /// See [AuthUserLocalEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<AuthUserLocalEntity>(
    _entities[0].properties[25],
  );

  /// See [AuthUserLocalEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<AuthUserLocalEntity>(
    _entities[0].properties[26],
  );

  /// See [AuthUserLocalEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<AuthUserLocalEntity>(
    _entities[0].properties[27],
  );

  /// See [AuthUserLocalEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AuthUserLocalEntity>(
    _entities[0].properties[28],
  );

  /// See [AuthUserLocalEntity.loginTime].
  static final loginTime = obx.QueryDateProperty<AuthUserLocalEntity>(
    _entities[0].properties[29],
  );

  /// see [AuthUserLocalEntity.devices]
  static final devices =
      obx.QueryBacklinkToMany<AuthUserDeviceEntity, AuthUserLocalEntity>(
        AuthUserDeviceEntity_.user,
      );
}

/// [AuthUserDeviceEntity] entity fields to define ObjectBox queries.
class AuthUserDeviceEntity_ {
  /// See [AuthUserDeviceEntity.id].
  static final id = obx.QueryIntegerProperty<AuthUserDeviceEntity>(
    _entities[1].properties[0],
  );

  /// See [AuthUserDeviceEntity.deviceToken].
  static final deviceToken = obx.QueryStringProperty<AuthUserDeviceEntity>(
    _entities[1].properties[1],
  );

  /// See [AuthUserDeviceEntity.deviceType].
  static final deviceType = obx.QueryStringProperty<AuthUserDeviceEntity>(
    _entities[1].properties[2],
  );

  /// See [AuthUserDeviceEntity.user].
  static final user =
      obx.QueryRelationToOne<AuthUserDeviceEntity, AuthUserLocalEntity>(
        _entities[1].properties[3],
      );
}
