// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth_flow/data/datasources/local_datasources/auth_user_local_entity.dart';
import 'features/auth_flow/domain/entities/icc_document_entity.dart';
import 'features/auth_flow/domain/entities/inspector_sign_up_entity.dart';
import 'features/auth_flow/domain/entities/service_area_entity.dart';
import 'features/auth_flow/domain/entities/user_document_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6706348540238291838),
    name: 'AuthUserDeviceEntity',
    lastPropertyId: const obx_int.IdUid(4, 1656981505077753466),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7903789545280373362),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7276179211685549603),
        name: 'deviceToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5974167347893996918),
        name: 'deviceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1656981505077753466),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1381949025203565816),
        relationField: 'user',
        relationTarget: 'AuthUserLocalEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7510821947055321623),
    name: 'AuthUserLocalEntity',
    lastPropertyId: const obx_int.IdUid(59, 7978414809338223714),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4977728006046384477),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8628880249020340326),
        name: 'authToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7448645097453528156),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3400367580876140345),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9159726942363196862),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9074335077169029502),
        name: 'countryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7142021894114820947),
        name: 'mailingAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3761681116789920791),
        name: 'role',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8622226598331293884),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 96454780337836301),
        name: 'phoneOtpVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2748252265901843734),
        name: 'emailOtpVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6067500703375922462),
        name: 'agreedToTerms',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8693323874627607521),
        name: 'isTruthfully',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 815433817228123830),
        name: 'rejectedReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4710430893609031014),
        name: 'stripeCustomerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4710107865299513468),
        name: 'stripeAccountId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8933747536940468220),
        name: 'stripePayoutsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7589101533977070173),
        name: 'currentSubscriptionTrialDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2205212665702389342),
        name: 'currentSubscriptionAutoRenew',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 1561577677941793754),
        name: 'stripeSubscriptionStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 1696120360638824616),
        name: 'walletId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 4241434292874720691),
        name: 'locationName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 4844683456458531299),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5180203900191409144),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 1461643812927463339),
        name: 'profileImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 2939544253580277981),
        name: 'bookingInProgress',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 7455222307864686066),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 2310972432133450897),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 2108784632282699482),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 1683338692122169949),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 7707187672438981528),
        name: 'certificateTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 3812095102116327804),
        name: 'certificateAgencyIds',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 1322619594078037508),
        name: 'certificateDocuments',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 8318957044173853223),
        name: 'certificateExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 6683843560515343898),
        name: 'referenceDocuments',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 7361908397267452669),
        name: 'workHistoryDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 8768948039023014530),
        name: 'zipCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(45, 5289162330176025876),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(46, 2778237008367224666),
        name: 'certificateApproved',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(47, 3087368259834947786),
        name: 'stripeTransfersEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(48, 5938988651120465848),
        name: 'statusUpdatedByAdmin',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(49, 1903062305422906928),
        name: 'docxOk',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(50, 1671177585830292350),
        name: 'connectorLinkUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(51, 6280060655161164616),
        name: 'documentTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(52, 2941370578795659748),
        name: 'documentExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(53, 3411826669160965555),
        name: 'coiExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(54, 1713348069903800072),
        name: 'serviceAreasJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(55, 8381573198068334159),
        name: 'documentsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(56, 1505627364880832062),
        name: 'certificateTypeJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(57, 6541931824567948546),
        name: 'noRejectedDocx',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(58, 6981807274895307395),
        name: 'lockedServiceCitiesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(59, 7978414809338223714),
        name: 'stripeConnectStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'devices',
        srcEntity: 'AuthUserDeviceEntity',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 9029954651202435050),
    name: 'ServiceAreaLocalEntity',
    lastPropertyId: const obx_int.IdUid(9, 1586819708624274860),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7019449212180121812),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2300943570772507507),
        name: 'countryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1194465841916251761),
        name: 'stateCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7668761717699029621),
        name: 'cityName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1519549142572183652),
        name: 'locationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 595672076555757210),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3415925726551865863),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2799346839572520102),
        name: 'inspectorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 7437307085727159997),
        relationField: 'inspector',
        relationTarget: 'InspectorSignUpLocalEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1586819708624274860),
        name: 'zipCode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1092552167430950126),
    name: 'IccDocumentLocalEntity',
    lastPropertyId: const obx_int.IdUid(7, 5187960889873647968),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8348989484481952739),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6667415046504984302),
        name: 'serviceCity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1311932127798013556),
        name: 'documentUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3418233597536894974),
        name: 'expiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2791628972036703477),
        name: 'inspectorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 3003052939359749212),
        relationField: 'inspector',
        relationTarget: 'InspectorSignUpLocalEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1184967821527650118),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5187960889873647968),
        name: 'documentId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4587273844563843322),
    name: 'InspectorSignUpLocalEntity',
    lastPropertyId: const obx_int.IdUid(34, 2355455532701006726),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5020098889698739379),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5615088129383836506),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3290739183546745614),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5482189411535707384),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8019242808738564497),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1421595068287489865),
        name: 'countryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4506528872137946643),
        name: 'isoCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6515929450998926786),
        name: 'certificateTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1612338527414811929),
        name: 'certificateExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1019582268165397853),
        name: 'certificateDocuments',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4993553786436213980),
        name: 'certificateAgencyIds',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8338661027676363543),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7046861068969147304),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3531299557114550458),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2839191893435962444),
        name: 'zipCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8785152637027864370),
        name: 'mailingAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5802641083192084453),
        name: 'uploadedIdOrLicenseDocumentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1618354822361699326),
        relationField: 'uploadedIdOrLicenseDocument',
        relationTarget: 'UserDocumentEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1735611462436295217),
        name: 'uploadedCoiDocumentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 173099250557761874),
        relationField: 'uploadedCoiDocument',
        relationTarget: 'UserDocumentEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6057929060066387867),
        name: 'workHistoryDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 186085238766841993),
        name: 'referenceDocuments',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4554892896390134019),
        name: 'profileImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 7186940726255155259),
        name: 'agreedToTerms',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 5889660786884397806),
        name: 'isTruthfully',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3785514912352957683),
        name: 'role',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 6230045077504143326),
        name: 'deviceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 3845900890466634630),
        name: 'deviceToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5670669287489247476),
        name: 'locationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 1583353673002992247),
        name: 'locationName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 7716696653731028194),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 5684724542680354713),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 5135136386032267082),
        name: 'coiExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 6315401417057147495),
        name: 'documentExpiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 5102003578265939722),
        name: 'documentTypeId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'serviceAreas',
        srcEntity: 'ServiceAreaLocalEntity',
        srcField: 'inspector',
      ),
      obx_int.ModelBacklink(
        name: 'iccDocuments',
        srcEntity: 'IccDocumentLocalEntity',
        srcField: 'inspector',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2509113749129114289),
    name: 'UserDocumentEntity',
    lastPropertyId: const obx_int.IdUid(4, 2680068962258857928),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2783120034754568895),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3202520487701849351),
        name: 'documentUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8368635506498730413),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2680068962258857928),
        name: 'inspectorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 6544254131683991352),
        relationField: 'inspector',
        relationTarget: 'InspectorSignUpLocalEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 2509113749129114289),
    lastIndexId: const obx_int.IdUid(6, 6544254131683991352),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [9109420249064471506],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5058542504887666690,
      8140600119593809259,
      3730392305248784100,
      2822043330167833312,
      8563527971304190649,
      2827095630864152251,
      4508438178353477505,
      5337601937719951958,
      8984501950055425564,
      747165839657268135,
      1708947877299647342,
      8660919674515096567,
      4258692124644960770,
      217125110715837022,
      931265546274407687,
      3832810131687575410,
      4509228448113690047,
      3343242310044903772,
      5929173274600292394,
      2430642351229016959,
      6934937195310391165,
      3571384632198165329,
      1303636506337963961,
      8441941961876582789,
      6975515860393936727,
      3310720633964425158,
      8596761536149048617,
      7853610846225801814,
      868977506242046544,
      7537171130744517007,
      5656893369707610242,
      681259737902032796,
      8981014397423736499,
      5971348717096684686,
      879714024604332109,
      281102519960584207,
      281380528162074395,
      340893041376304159,
      2355455532701006726,
      8253652263703126921,
      3509022603680572381,
      5105618599375191812,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthUserDeviceEntity: obx_int.EntityDefinition<AuthUserDeviceEntity>(
      model: _entities[0],
      toOneRelations: (AuthUserDeviceEntity object) => [object.user],
      toManyRelations: (AuthUserDeviceEntity object) => {},
      getId: (AuthUserDeviceEntity object) => object.id,
      setId: (AuthUserDeviceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthUserDeviceEntity object, fb.Builder fbb) {
        final deviceTokenOffset = object.deviceToken == null
            ? null
            : fbb.writeString(object.deviceToken!);
        final deviceTypeOffset = object.deviceType == null
            ? null
            : fbb.writeString(object.deviceType!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceTokenOffset);
        fbb.addOffset(2, deviceTypeOffset);
        fbb.addInt64(3, object.user.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deviceTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final deviceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = AuthUserDeviceEntity(
          deviceToken: deviceTokenParam,
          deviceType: deviceTypeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
    AuthUserLocalEntity: obx_int.EntityDefinition<AuthUserLocalEntity>(
      model: _entities[1],
      toOneRelations: (AuthUserLocalEntity object) => [],
      toManyRelations: (AuthUserLocalEntity object) => {
        obx_int.RelInfo<AuthUserDeviceEntity>.toOneBacklink(
          4,
          object.id,
          (AuthUserDeviceEntity srcObject) => srcObject.user,
        ): object.devices,
      },
      getId: (AuthUserLocalEntity object) => object.id,
      setId: (AuthUserLocalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthUserLocalEntity object, fb.Builder fbb) {
        final authTokenOffset = object.authToken == null
            ? null
            : fbb.writeString(object.authToken!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final countryCodeOffset = object.countryCode == null
            ? null
            : fbb.writeString(object.countryCode!);
        final mailingAddressOffset = object.mailingAddress == null
            ? null
            : fbb.writeString(object.mailingAddress!);
        final rejectedReasonOffset = object.rejectedReason == null
            ? null
            : fbb.writeString(object.rejectedReason!);
        final stripeCustomerIdOffset = object.stripeCustomerId == null
            ? null
            : fbb.writeString(object.stripeCustomerId!);
        final stripeAccountIdOffset = object.stripeAccountId == null
            ? null
            : fbb.writeString(object.stripeAccountId!);
        final stripeSubscriptionStatusOffset =
            object.stripeSubscriptionStatus == null
            ? null
            : fbb.writeString(object.stripeSubscriptionStatus!);
        final walletIdOffset = object.walletId == null
            ? null
            : fbb.writeString(object.walletId!);
        final locationNameOffset = object.locationName == null
            ? null
            : fbb.writeString(object.locationName!);
        final profileImageOffset = object.profileImage == null
            ? null
            : fbb.writeString(object.profileImage!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final stateOffset = object.state == null
            ? null
            : fbb.writeString(object.state!);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final certificateTypeIdOffset = object.certificateTypeId == null
            ? null
            : fbb.writeString(object.certificateTypeId!);
        final certificateAgencyIdsOffset = object.certificateAgencyIds == null
            ? null
            : fbb.writeList(
                object.certificateAgencyIds!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final certificateDocumentsOffset = object.certificateDocuments == null
            ? null
            : fbb.writeList(
                object.certificateDocuments!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final certificateExpiryDateOffset = object.certificateExpiryDate == null
            ? null
            : fbb.writeString(object.certificateExpiryDate!);
        final referenceDocumentsOffset = object.referenceDocuments == null
            ? null
            : fbb.writeList(
                object.referenceDocuments!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final workHistoryDescriptionOffset =
            object.workHistoryDescription == null
            ? null
            : fbb.writeString(object.workHistoryDescription!);
        final zipCodeOffset = object.zipCode == null
            ? null
            : fbb.writeString(object.zipCode!);
        final userIdOffset = fbb.writeString(object.userId);
        final connectorLinkUrlOffset = object.connectorLinkUrl == null
            ? null
            : fbb.writeString(object.connectorLinkUrl!);
        final documentTypeIdOffset = object.documentTypeId == null
            ? null
            : fbb.writeString(object.documentTypeId!);
        final documentExpiryDateOffset = object.documentExpiryDate == null
            ? null
            : fbb.writeString(object.documentExpiryDate!);
        final coiExpiryDateOffset = object.coiExpiryDate == null
            ? null
            : fbb.writeString(object.coiExpiryDate!);
        final serviceAreasJsonOffset = object.serviceAreasJson == null
            ? null
            : fbb.writeString(object.serviceAreasJson!);
        final documentsJsonOffset = object.documentsJson == null
            ? null
            : fbb.writeString(object.documentsJson!);
        final certificateTypeJsonOffset = object.certificateTypeJson == null
            ? null
            : fbb.writeString(object.certificateTypeJson!);
        final lockedServiceCitiesJsonOffset =
            object.lockedServiceCitiesJson == null
            ? null
            : fbb.writeString(object.lockedServiceCitiesJson!);
        final stripeConnectStatusOffset = object.stripeConnectStatus == null
            ? null
            : fbb.writeString(object.stripeConnectStatus!);
        fbb.startTable(60);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, authTokenOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(4, phoneNumberOffset);
        fbb.addOffset(5, countryCodeOffset);
        fbb.addOffset(6, mailingAddressOffset);
        fbb.addInt64(7, object.role);
        fbb.addInt64(8, object.status);
        fbb.addBool(9, object.phoneOtpVerified);
        fbb.addBool(10, object.emailOtpVerified);
        fbb.addBool(11, object.agreedToTerms);
        fbb.addBool(12, object.isTruthfully);
        fbb.addOffset(14, rejectedReasonOffset);
        fbb.addOffset(15, stripeCustomerIdOffset);
        fbb.addOffset(16, stripeAccountIdOffset);
        fbb.addBool(17, object.stripePayoutsEnabled);
        fbb.addInt64(19, object.currentSubscriptionTrialDays);
        fbb.addInt64(20, object.currentSubscriptionAutoRenew);
        fbb.addOffset(22, stripeSubscriptionStatusOffset);
        fbb.addOffset(23, walletIdOffset);
        fbb.addOffset(24, locationNameOffset);
        fbb.addFloat64(25, object.latitude);
        fbb.addFloat64(26, object.longitude);
        fbb.addOffset(29, profileImageOffset);
        fbb.addBool(30, object.bookingInProgress);
        fbb.addBool(31, object.isDeleted);
        fbb.addOffset(32, countryOffset);
        fbb.addOffset(33, stateOffset);
        fbb.addOffset(34, cityOffset);
        fbb.addOffset(35, certificateTypeIdOffset);
        fbb.addOffset(36, certificateAgencyIdsOffset);
        fbb.addOffset(37, certificateDocumentsOffset);
        fbb.addOffset(38, certificateExpiryDateOffset);
        fbb.addOffset(39, referenceDocumentsOffset);
        fbb.addOffset(41, workHistoryDescriptionOffset);
        fbb.addOffset(43, zipCodeOffset);
        fbb.addOffset(44, userIdOffset);
        fbb.addInt64(45, object.certificateApproved);
        fbb.addBool(46, object.stripeTransfersEnabled);
        fbb.addBool(47, object.statusUpdatedByAdmin);
        fbb.addInt64(48, object.docxOk);
        fbb.addOffset(49, connectorLinkUrlOffset);
        fbb.addOffset(50, documentTypeIdOffset);
        fbb.addOffset(51, documentExpiryDateOffset);
        fbb.addOffset(52, coiExpiryDateOffset);
        fbb.addOffset(53, serviceAreasJsonOffset);
        fbb.addOffset(54, documentsJsonOffset);
        fbb.addOffset(55, certificateTypeJsonOffset);
        fbb.addBool(56, object.noRejectedDocx);
        fbb.addOffset(57, lockedServiceCitiesJsonOffset);
        fbb.addOffset(58, stripeConnectStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 92, '');
        final authTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final countryCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final mailingAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final roleParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final statusParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final phoneOtpVerifiedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final emailOtpVerifiedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final agreedToTermsParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final isTruthfullyParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final statusUpdatedByAdminParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 98);
        final certificateApprovedParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 94);
        final certificateTypeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 74);
        final certificateTypeJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 114);
        final certificateAgencyIdsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 76);
        final certificateDocumentsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 78);
        final certificateExpiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 80);
        final noRejectedDocxParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          116,
        );
        final documentTypeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 104);
        final documentExpiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 106);
        final coiExpiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 108);
        final documentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 112);
        final serviceAreasJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 110);
        final lockedServiceCitiesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 118);
        final docxOkParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          100,
        );
        final profileImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final bookingInProgressParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          64,
        );
        final isDeletedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          66,
        );
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 68);
        final stateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 70);
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 72);
        final zipCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 90);
        final locationNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final stripeCustomerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final stripeAccountIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final stripePayoutsEnabledParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 38);
        final stripeTransfersEnabledParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 96);
        final stripeSubscriptionStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final stripeConnectStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 120);
        final currentSubscriptionTrialDaysParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final currentSubscriptionAutoRenewParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 44);
        final walletIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final connectorLinkUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 102);
        final rejectedReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final workHistoryDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 86);
        final referenceDocumentsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 82);
        final object = AuthUserLocalEntity(
          userId: userIdParam,
          authToken: authTokenParam,
          name: nameParam,
          email: emailParam,
          phoneNumber: phoneNumberParam,
          countryCode: countryCodeParam,
          mailingAddress: mailingAddressParam,
          role: roleParam,
          status: statusParam,
          phoneOtpVerified: phoneOtpVerifiedParam,
          emailOtpVerified: emailOtpVerifiedParam,
          agreedToTerms: agreedToTermsParam,
          isTruthfully: isTruthfullyParam,
          statusUpdatedByAdmin: statusUpdatedByAdminParam,
          certificateApproved: certificateApprovedParam,
          certificateTypeId: certificateTypeIdParam,
          certificateTypeJson: certificateTypeJsonParam,
          certificateAgencyIds: certificateAgencyIdsParam,
          certificateDocuments: certificateDocumentsParam,
          certificateExpiryDate: certificateExpiryDateParam,
          noRejectedDocx: noRejectedDocxParam,
          documentTypeId: documentTypeIdParam,
          documentExpiryDate: documentExpiryDateParam,
          coiExpiryDate: coiExpiryDateParam,
          documentsJson: documentsJsonParam,
          serviceAreasJson: serviceAreasJsonParam,
          lockedServiceCitiesJson: lockedServiceCitiesJsonParam,
          docxOk: docxOkParam,
          profileImage: profileImageParam,
          bookingInProgress: bookingInProgressParam,
          isDeleted: isDeletedParam,
          country: countryParam,
          state: stateParam,
          city: cityParam,
          zipCode: zipCodeParam,
          locationName: locationNameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          stripeCustomerId: stripeCustomerIdParam,
          stripeAccountId: stripeAccountIdParam,
          stripePayoutsEnabled: stripePayoutsEnabledParam,
          stripeTransfersEnabled: stripeTransfersEnabledParam,
          stripeSubscriptionStatus: stripeSubscriptionStatusParam,
          stripeConnectStatus: stripeConnectStatusParam,
          currentSubscriptionTrialDays: currentSubscriptionTrialDaysParam,
          currentSubscriptionAutoRenew: currentSubscriptionAutoRenewParam,
          walletId: walletIdParam,
          connectorLinkUrl: connectorLinkUrlParam,
          rejectedReason: rejectedReasonParam,
          workHistoryDescription: workHistoryDescriptionParam,
          referenceDocuments: referenceDocumentsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<AuthUserLocalEntity>(
          object.devices,
          store,
          obx_int.RelInfo<AuthUserDeviceEntity>.toOneBacklink(
            4,
            object.id,
            (AuthUserDeviceEntity srcObject) => srcObject.user,
          ),
        );
        return object;
      },
    ),
    ServiceAreaLocalEntity: obx_int.EntityDefinition<ServiceAreaLocalEntity>(
      model: _entities[2],
      toOneRelations: (ServiceAreaLocalEntity object) => [object.inspector],
      toManyRelations: (ServiceAreaLocalEntity object) => {},
      getId: (ServiceAreaLocalEntity object) => object.id,
      setId: (ServiceAreaLocalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ServiceAreaLocalEntity object, fb.Builder fbb) {
        final countryCodeOffset = object.countryCode == null
            ? null
            : fbb.writeString(object.countryCode!);
        final stateCodeOffset = object.stateCode == null
            ? null
            : fbb.writeString(object.stateCode!);
        final cityNameOffset = object.cityName == null
            ? null
            : fbb.writeString(object.cityName!);
        final locationTypeOffset = object.locationType == null
            ? null
            : fbb.writeString(object.locationType!);
        final zipCodeOffset = object.zipCode == null
            ? null
            : fbb.writeString(object.zipCode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, countryCodeOffset);
        fbb.addOffset(2, stateCodeOffset);
        fbb.addOffset(3, cityNameOffset);
        fbb.addOffset(4, locationTypeOffset);
        fbb.addFloat64(5, object.latitude);
        fbb.addFloat64(6, object.longitude);
        fbb.addInt64(7, object.inspector.targetId);
        fbb.addOffset(8, zipCodeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final countryCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final stateCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final cityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final zipCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final locationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = ServiceAreaLocalEntity(
          id: idParam,
          countryCode: countryCodeParam,
          stateCode: stateCodeParam,
          cityName: cityNameParam,
          zipCode: zipCodeParam,
          locationType: locationTypeParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
        );
        object.inspector.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.inspector.attach(store);
        return object;
      },
    ),
    IccDocumentLocalEntity: obx_int.EntityDefinition<IccDocumentLocalEntity>(
      model: _entities[3],
      toOneRelations: (IccDocumentLocalEntity object) => [object.inspector],
      toManyRelations: (IccDocumentLocalEntity object) => {},
      getId: (IccDocumentLocalEntity object) => object.id,
      setId: (IccDocumentLocalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (IccDocumentLocalEntity object, fb.Builder fbb) {
        final serviceCityOffset = fbb.writeString(object.serviceCity);
        final documentUrlOffset = fbb.writeString(object.documentUrl);
        final expiryDateOffset = fbb.writeString(object.expiryDate);
        final fileNameOffset = fbb.writeString(object.fileName);
        final documentIdOffset = fbb.writeString(object.documentId);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serviceCityOffset);
        fbb.addOffset(2, documentUrlOffset);
        fbb.addOffset(3, expiryDateOffset);
        fbb.addInt64(4, object.inspector.targetId);
        fbb.addOffset(5, fileNameOffset);
        fbb.addOffset(6, documentIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serviceCityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final documentUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final expiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final documentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = IccDocumentLocalEntity(
          id: idParam,
          serviceCity: serviceCityParam,
          documentUrl: documentUrlParam,
          expiryDate: expiryDateParam,
          fileName: fileNameParam,
          documentId: documentIdParam,
        );
        object.inspector.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.inspector.attach(store);
        return object;
      },
    ),
    InspectorSignUpLocalEntity:
        obx_int.EntityDefinition<InspectorSignUpLocalEntity>(
          model: _entities[4],
          toOneRelations: (InspectorSignUpLocalEntity object) => [
            object.uploadedIdOrLicenseDocument,
            object.uploadedCoiDocument,
          ],
          toManyRelations: (InspectorSignUpLocalEntity object) => {
            obx_int.RelInfo<ServiceAreaLocalEntity>.toOneBacklink(
              8,
              object.id,
              (ServiceAreaLocalEntity srcObject) => srcObject.inspector,
            ): object.serviceAreas,
            obx_int.RelInfo<IccDocumentLocalEntity>.toOneBacklink(
              5,
              object.id,
              (IccDocumentLocalEntity srcObject) => srcObject.inspector,
            ): object.iccDocuments,
          },
          getId: (InspectorSignUpLocalEntity object) => object.id,
          setId: (InspectorSignUpLocalEntity object, int id) {
            object.id = id;
          },
          objectToFB: (InspectorSignUpLocalEntity object, fb.Builder fbb) {
            final nameOffset = object.name == null
                ? null
                : fbb.writeString(object.name!);
            final emailOffset = object.email == null
                ? null
                : fbb.writeString(object.email!);
            final passwordOffset = object.password == null
                ? null
                : fbb.writeString(object.password!);
            final phoneNumberOffset = object.phoneNumber == null
                ? null
                : fbb.writeString(object.phoneNumber!);
            final countryCodeOffset = object.countryCode == null
                ? null
                : fbb.writeString(object.countryCode!);
            final isoCodeOffset = object.isoCode == null
                ? null
                : fbb.writeString(object.isoCode!);
            final certificateTypeIdOffset = object.certificateTypeId == null
                ? null
                : fbb.writeString(object.certificateTypeId!);
            final certificateExpiryDateOffset =
                object.certificateExpiryDate == null
                ? null
                : fbb.writeString(object.certificateExpiryDate!);
            final certificateDocumentsOffset =
                object.certificateDocuments == null
                ? null
                : fbb.writeList(
                    object.certificateDocuments!
                        .map(fbb.writeString)
                        .toList(growable: false),
                  );
            final certificateAgencyIdsOffset =
                object.certificateAgencyIds == null
                ? null
                : fbb.writeList(
                    object.certificateAgencyIds!
                        .map(fbb.writeString)
                        .toList(growable: false),
                  );
            final countryOffset = object.country == null
                ? null
                : fbb.writeString(object.country!);
            final stateOffset = object.state == null
                ? null
                : fbb.writeString(object.state!);
            final cityOffset = object.city == null
                ? null
                : fbb.writeString(object.city!);
            final zipCodeOffset = object.zipCode == null
                ? null
                : fbb.writeString(object.zipCode!);
            final mailingAddressOffset = object.mailingAddress == null
                ? null
                : fbb.writeString(object.mailingAddress!);
            final workHistoryDescriptionOffset =
                object.workHistoryDescription == null
                ? null
                : fbb.writeString(object.workHistoryDescription!);
            final referenceDocumentsOffset = object.referenceDocuments == null
                ? null
                : fbb.writeList(
                    object.referenceDocuments!
                        .map(fbb.writeString)
                        .toList(growable: false),
                  );
            final profileImageOffset = object.profileImage == null
                ? null
                : fbb.writeString(object.profileImage!);
            final deviceTypeOffset = object.deviceType == null
                ? null
                : fbb.writeString(object.deviceType!);
            final deviceTokenOffset = object.deviceToken == null
                ? null
                : fbb.writeString(object.deviceToken!);
            final locationTypeOffset = object.locationType == null
                ? null
                : fbb.writeString(object.locationType!);
            final locationNameOffset = object.locationName == null
                ? null
                : fbb.writeString(object.locationName!);
            final coiExpiryDateOffset = object.coiExpiryDate == null
                ? null
                : fbb.writeString(object.coiExpiryDate!);
            final documentExpiryDateOffset = object.documentExpiryDate == null
                ? null
                : fbb.writeString(object.documentExpiryDate!);
            final documentTypeIdOffset = object.documentTypeId == null
                ? null
                : fbb.writeString(object.documentTypeId!);
            fbb.startTable(35);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, nameOffset);
            fbb.addOffset(2, emailOffset);
            fbb.addOffset(3, passwordOffset);
            fbb.addOffset(4, phoneNumberOffset);
            fbb.addOffset(5, countryCodeOffset);
            fbb.addOffset(6, isoCodeOffset);
            fbb.addOffset(7, certificateTypeIdOffset);
            fbb.addOffset(8, certificateExpiryDateOffset);
            fbb.addOffset(9, certificateDocumentsOffset);
            fbb.addOffset(10, certificateAgencyIdsOffset);
            fbb.addOffset(11, countryOffset);
            fbb.addOffset(12, stateOffset);
            fbb.addOffset(13, cityOffset);
            fbb.addOffset(14, zipCodeOffset);
            fbb.addOffset(15, mailingAddressOffset);
            fbb.addInt64(16, object.uploadedIdOrLicenseDocument.targetId);
            fbb.addInt64(17, object.uploadedCoiDocument.targetId);
            fbb.addOffset(18, workHistoryDescriptionOffset);
            fbb.addOffset(19, referenceDocumentsOffset);
            fbb.addOffset(20, profileImageOffset);
            fbb.addBool(21, object.agreedToTerms);
            fbb.addBool(22, object.isTruthfully);
            fbb.addInt64(23, object.role);
            fbb.addOffset(24, deviceTypeOffset);
            fbb.addOffset(25, deviceTokenOffset);
            fbb.addOffset(26, locationTypeOffset);
            fbb.addOffset(27, locationNameOffset);
            fbb.addFloat64(28, object.latitude);
            fbb.addFloat64(29, object.longitude);
            fbb.addOffset(30, coiExpiryDateOffset);
            fbb.addOffset(31, documentExpiryDateOffset);
            fbb.addOffset(32, documentTypeIdOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 6);
            final emailParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 8);
            final passwordParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 10);
            final phoneNumberParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 12);
            final countryCodeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 14);
            final isoCodeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 16);
            final certificateTypeIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 18);
            final certificateExpiryDateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 20);
            final certificateDocumentsParam = const fb.ListReader<String>(
              fb.StringReader(asciiOptimization: true),
              lazy: false,
            ).vTableGetNullable(buffer, rootOffset, 22);
            final certificateAgencyIdsParam = const fb.ListReader<String>(
              fb.StringReader(asciiOptimization: true),
              lazy: false,
            ).vTableGetNullable(buffer, rootOffset, 24);
            final countryParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 26);
            final stateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 28);
            final cityParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 30);
            final zipCodeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 32);
            final mailingAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 34);
            final workHistoryDescriptionParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 40);
            final referenceDocumentsParam = const fb.ListReader<String>(
              fb.StringReader(asciiOptimization: true),
              lazy: false,
            ).vTableGetNullable(buffer, rootOffset, 42);
            final profileImageParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 44);
            final agreedToTermsParam = const fb.BoolReader().vTableGetNullable(
              buffer,
              rootOffset,
              46,
            );
            final isTruthfullyParam = const fb.BoolReader().vTableGetNullable(
              buffer,
              rootOffset,
              48,
            );
            final roleParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              50,
            );
            final deviceTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 52);
            final deviceTokenParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 54);
            final locationTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 56);
            final locationNameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 58);
            final latitudeParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              60,
            );
            final longitudeParam = const fb.Float64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              62,
            );
            final coiExpiryDateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 64);
            final documentExpiryDateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 66);
            final documentTypeIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 68);
            final object = InspectorSignUpLocalEntity(
              id: idParam,
              name: nameParam,
              email: emailParam,
              password: passwordParam,
              phoneNumber: phoneNumberParam,
              countryCode: countryCodeParam,
              isoCode: isoCodeParam,
              certificateTypeId: certificateTypeIdParam,
              certificateExpiryDate: certificateExpiryDateParam,
              certificateDocuments: certificateDocumentsParam,
              certificateAgencyIds: certificateAgencyIdsParam,
              country: countryParam,
              state: stateParam,
              city: cityParam,
              zipCode: zipCodeParam,
              mailingAddress: mailingAddressParam,
              workHistoryDescription: workHistoryDescriptionParam,
              referenceDocuments: referenceDocumentsParam,
              profileImage: profileImageParam,
              agreedToTerms: agreedToTermsParam,
              isTruthfully: isTruthfullyParam,
              role: roleParam,
              deviceType: deviceTypeParam,
              deviceToken: deviceTokenParam,
              locationType: locationTypeParam,
              locationName: locationNameParam,
              latitude: latitudeParam,
              longitude: longitudeParam,
              coiExpiryDate: coiExpiryDateParam,
              documentExpiryDate: documentExpiryDateParam,
              documentTypeId: documentTypeIdParam,
            );
            object.uploadedIdOrLicenseDocument.targetId = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 36, 0);
            object.uploadedIdOrLicenseDocument.attach(store);
            object.uploadedCoiDocument.targetId = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 38, 0);
            object.uploadedCoiDocument.attach(store);
            obx_int.InternalToManyAccess.setRelInfo<InspectorSignUpLocalEntity>(
              object.serviceAreas,
              store,
              obx_int.RelInfo<ServiceAreaLocalEntity>.toOneBacklink(
                8,
                object.id,
                (ServiceAreaLocalEntity srcObject) => srcObject.inspector,
              ),
            );
            obx_int.InternalToManyAccess.setRelInfo<InspectorSignUpLocalEntity>(
              object.iccDocuments,
              store,
              obx_int.RelInfo<IccDocumentLocalEntity>.toOneBacklink(
                5,
                object.id,
                (IccDocumentLocalEntity srcObject) => srcObject.inspector,
              ),
            );
            return object;
          },
        ),
    UserDocumentEntity: obx_int.EntityDefinition<UserDocumentEntity>(
      model: _entities[5],
      toOneRelations: (UserDocumentEntity object) => [object.inspector],
      toManyRelations: (UserDocumentEntity object) => {},
      getId: (UserDocumentEntity object) => object.id,
      setId: (UserDocumentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserDocumentEntity object, fb.Builder fbb) {
        final documentUrlOffset = object.documentUrl == null
            ? null
            : fbb.writeString(object.documentUrl!);
        final fileNameOffset = object.fileName == null
            ? null
            : fbb.writeString(object.fileName!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, documentUrlOffset);
        fbb.addOffset(2, fileNameOffset);
        fbb.addInt64(3, object.inspector.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final documentUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = UserDocumentEntity(
          id: idParam,
          documentUrl: documentUrlParam,
          fileName: fileNameParam,
        );
        object.inspector.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.inspector.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthUserDeviceEntity] entity fields to define ObjectBox queries.
class AuthUserDeviceEntity_ {
  /// See [AuthUserDeviceEntity.id].
  static final id = obx.QueryIntegerProperty<AuthUserDeviceEntity>(
    _entities[0].properties[0],
  );

  /// See [AuthUserDeviceEntity.deviceToken].
  static final deviceToken = obx.QueryStringProperty<AuthUserDeviceEntity>(
    _entities[0].properties[1],
  );

  /// See [AuthUserDeviceEntity.deviceType].
  static final deviceType = obx.QueryStringProperty<AuthUserDeviceEntity>(
    _entities[0].properties[2],
  );

  /// See [AuthUserDeviceEntity.user].
  static final user =
      obx.QueryRelationToOne<AuthUserDeviceEntity, AuthUserLocalEntity>(
        _entities[0].properties[3],
      );
}

/// [AuthUserLocalEntity] entity fields to define ObjectBox queries.
class AuthUserLocalEntity_ {
  /// See [AuthUserLocalEntity.id].
  static final id = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[1].properties[0],
  );

  /// See [AuthUserLocalEntity.authToken].
  static final authToken = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[1],
  );

  /// See [AuthUserLocalEntity.name].
  static final name = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[2],
  );

  /// See [AuthUserLocalEntity.email].
  static final email = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[3],
  );

  /// See [AuthUserLocalEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[4],
  );

  /// See [AuthUserLocalEntity.countryCode].
  static final countryCode = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[5],
  );

  /// See [AuthUserLocalEntity.mailingAddress].
  static final mailingAddress = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[6],
  );

  /// See [AuthUserLocalEntity.role].
  static final role = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[1].properties[7],
  );

  /// See [AuthUserLocalEntity.status].
  static final status = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[1].properties[8],
  );

  /// See [AuthUserLocalEntity.phoneOtpVerified].
  static final phoneOtpVerified = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[9],
  );

  /// See [AuthUserLocalEntity.emailOtpVerified].
  static final emailOtpVerified = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[10],
  );

  /// See [AuthUserLocalEntity.agreedToTerms].
  static final agreedToTerms = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[11],
  );

  /// See [AuthUserLocalEntity.isTruthfully].
  static final isTruthfully = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[12],
  );

  /// See [AuthUserLocalEntity.rejectedReason].
  static final rejectedReason = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[13],
  );

  /// See [AuthUserLocalEntity.stripeCustomerId].
  static final stripeCustomerId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[14],
  );

  /// See [AuthUserLocalEntity.stripeAccountId].
  static final stripeAccountId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[15],
  );

  /// See [AuthUserLocalEntity.stripePayoutsEnabled].
  static final stripePayoutsEnabled =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[1].properties[16],
      );

  /// See [AuthUserLocalEntity.currentSubscriptionTrialDays].
  static final currentSubscriptionTrialDays =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[1].properties[17],
      );

  /// See [AuthUserLocalEntity.currentSubscriptionAutoRenew].
  static final currentSubscriptionAutoRenew =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[1].properties[18],
      );

  /// See [AuthUserLocalEntity.stripeSubscriptionStatus].
  static final stripeSubscriptionStatus =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[19]);

  /// See [AuthUserLocalEntity.walletId].
  static final walletId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[20],
  );

  /// See [AuthUserLocalEntity.locationName].
  static final locationName = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[21],
  );

  /// See [AuthUserLocalEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<AuthUserLocalEntity>(
    _entities[1].properties[22],
  );

  /// See [AuthUserLocalEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<AuthUserLocalEntity>(
    _entities[1].properties[23],
  );

  /// See [AuthUserLocalEntity.profileImage].
  static final profileImage = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[24],
  );

  /// See [AuthUserLocalEntity.bookingInProgress].
  static final bookingInProgress =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[1].properties[25],
      );

  /// See [AuthUserLocalEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[26],
  );

  /// See [AuthUserLocalEntity.country].
  static final country = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[27],
  );

  /// See [AuthUserLocalEntity.state].
  static final state = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[28],
  );

  /// See [AuthUserLocalEntity.city].
  static final city = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[29],
  );

  /// See [AuthUserLocalEntity.certificateTypeId].
  static final certificateTypeId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[30],
  );

  /// See [AuthUserLocalEntity.certificateAgencyIds].
  static final certificateAgencyIds =
      obx.QueryStringVectorProperty<AuthUserLocalEntity>(
        _entities[1].properties[31],
      );

  /// See [AuthUserLocalEntity.certificateDocuments].
  static final certificateDocuments =
      obx.QueryStringVectorProperty<AuthUserLocalEntity>(
        _entities[1].properties[32],
      );

  /// See [AuthUserLocalEntity.certificateExpiryDate].
  static final certificateExpiryDate =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[33]);

  /// See [AuthUserLocalEntity.referenceDocuments].
  static final referenceDocuments =
      obx.QueryStringVectorProperty<AuthUserLocalEntity>(
        _entities[1].properties[34],
      );

  /// See [AuthUserLocalEntity.workHistoryDescription].
  static final workHistoryDescription =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[35]);

  /// See [AuthUserLocalEntity.zipCode].
  static final zipCode = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[36],
  );

  /// See [AuthUserLocalEntity.userId].
  static final userId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[37],
  );

  /// See [AuthUserLocalEntity.certificateApproved].
  static final certificateApproved =
      obx.QueryIntegerProperty<AuthUserLocalEntity>(
        _entities[1].properties[38],
      );

  /// See [AuthUserLocalEntity.stripeTransfersEnabled].
  static final stripeTransfersEnabled =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[1].properties[39],
      );

  /// See [AuthUserLocalEntity.statusUpdatedByAdmin].
  static final statusUpdatedByAdmin =
      obx.QueryBooleanProperty<AuthUserLocalEntity>(
        _entities[1].properties[40],
      );

  /// See [AuthUserLocalEntity.docxOk].
  static final docxOk = obx.QueryIntegerProperty<AuthUserLocalEntity>(
    _entities[1].properties[41],
  );

  /// See [AuthUserLocalEntity.connectorLinkUrl].
  static final connectorLinkUrl = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[42],
  );

  /// See [AuthUserLocalEntity.documentTypeId].
  static final documentTypeId = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[43],
  );

  /// See [AuthUserLocalEntity.documentExpiryDate].
  static final documentExpiryDate =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[44]);

  /// See [AuthUserLocalEntity.coiExpiryDate].
  static final coiExpiryDate = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[45],
  );

  /// See [AuthUserLocalEntity.serviceAreasJson].
  static final serviceAreasJson = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[46],
  );

  /// See [AuthUserLocalEntity.documentsJson].
  static final documentsJson = obx.QueryStringProperty<AuthUserLocalEntity>(
    _entities[1].properties[47],
  );

  /// See [AuthUserLocalEntity.certificateTypeJson].
  static final certificateTypeJson =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[48]);

  /// See [AuthUserLocalEntity.noRejectedDocx].
  static final noRejectedDocx = obx.QueryBooleanProperty<AuthUserLocalEntity>(
    _entities[1].properties[49],
  );

  /// See [AuthUserLocalEntity.lockedServiceCitiesJson].
  static final lockedServiceCitiesJson =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[50]);

  /// See [AuthUserLocalEntity.stripeConnectStatus].
  static final stripeConnectStatus =
      obx.QueryStringProperty<AuthUserLocalEntity>(_entities[1].properties[51]);

  /// see [AuthUserLocalEntity.devices]
  static final devices =
      obx.QueryBacklinkToMany<AuthUserDeviceEntity, AuthUserLocalEntity>(
        AuthUserDeviceEntity_.user,
      );
}

/// [ServiceAreaLocalEntity] entity fields to define ObjectBox queries.
class ServiceAreaLocalEntity_ {
  /// See [ServiceAreaLocalEntity.id].
  static final id = obx.QueryIntegerProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[0],
  );

  /// See [ServiceAreaLocalEntity.countryCode].
  static final countryCode = obx.QueryStringProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[1],
  );

  /// See [ServiceAreaLocalEntity.stateCode].
  static final stateCode = obx.QueryStringProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[2],
  );

  /// See [ServiceAreaLocalEntity.cityName].
  static final cityName = obx.QueryStringProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[3],
  );

  /// See [ServiceAreaLocalEntity.locationType].
  static final locationType = obx.QueryStringProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[4],
  );

  /// See [ServiceAreaLocalEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[5],
  );

  /// See [ServiceAreaLocalEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[6],
  );

  /// See [ServiceAreaLocalEntity.inspector].
  static final inspector =
      obx.QueryRelationToOne<
        ServiceAreaLocalEntity,
        InspectorSignUpLocalEntity
      >(_entities[2].properties[7]);

  /// See [ServiceAreaLocalEntity.zipCode].
  static final zipCode = obx.QueryStringProperty<ServiceAreaLocalEntity>(
    _entities[2].properties[8],
  );
}

/// [IccDocumentLocalEntity] entity fields to define ObjectBox queries.
class IccDocumentLocalEntity_ {
  /// See [IccDocumentLocalEntity.id].
  static final id = obx.QueryIntegerProperty<IccDocumentLocalEntity>(
    _entities[3].properties[0],
  );

  /// See [IccDocumentLocalEntity.serviceCity].
  static final serviceCity = obx.QueryStringProperty<IccDocumentLocalEntity>(
    _entities[3].properties[1],
  );

  /// See [IccDocumentLocalEntity.documentUrl].
  static final documentUrl = obx.QueryStringProperty<IccDocumentLocalEntity>(
    _entities[3].properties[2],
  );

  /// See [IccDocumentLocalEntity.expiryDate].
  static final expiryDate = obx.QueryStringProperty<IccDocumentLocalEntity>(
    _entities[3].properties[3],
  );

  /// See [IccDocumentLocalEntity.inspector].
  static final inspector =
      obx.QueryRelationToOne<
        IccDocumentLocalEntity,
        InspectorSignUpLocalEntity
      >(_entities[3].properties[4]);

  /// See [IccDocumentLocalEntity.fileName].
  static final fileName = obx.QueryStringProperty<IccDocumentLocalEntity>(
    _entities[3].properties[5],
  );

  /// See [IccDocumentLocalEntity.documentId].
  static final documentId = obx.QueryStringProperty<IccDocumentLocalEntity>(
    _entities[3].properties[6],
  );
}

/// [InspectorSignUpLocalEntity] entity fields to define ObjectBox queries.
class InspectorSignUpLocalEntity_ {
  /// See [InspectorSignUpLocalEntity.id].
  static final id = obx.QueryIntegerProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[0],
  );

  /// See [InspectorSignUpLocalEntity.name].
  static final name = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[1],
  );

  /// See [InspectorSignUpLocalEntity.email].
  static final email = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[2],
  );

  /// See [InspectorSignUpLocalEntity.password].
  static final password = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[3],
  );

  /// See [InspectorSignUpLocalEntity.phoneNumber].
  static final phoneNumber =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[4],
      );

  /// See [InspectorSignUpLocalEntity.countryCode].
  static final countryCode =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[5],
      );

  /// See [InspectorSignUpLocalEntity.isoCode].
  static final isoCode = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[6],
  );

  /// See [InspectorSignUpLocalEntity.certificateTypeId].
  static final certificateTypeId =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[7],
      );

  /// See [InspectorSignUpLocalEntity.certificateExpiryDate].
  static final certificateExpiryDate =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[8],
      );

  /// See [InspectorSignUpLocalEntity.certificateDocuments].
  static final certificateDocuments =
      obx.QueryStringVectorProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[9],
      );

  /// See [InspectorSignUpLocalEntity.certificateAgencyIds].
  static final certificateAgencyIds =
      obx.QueryStringVectorProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[10],
      );

  /// See [InspectorSignUpLocalEntity.country].
  static final country = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[11],
  );

  /// See [InspectorSignUpLocalEntity.state].
  static final state = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[12],
  );

  /// See [InspectorSignUpLocalEntity.city].
  static final city = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[13],
  );

  /// See [InspectorSignUpLocalEntity.zipCode].
  static final zipCode = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[14],
  );

  /// See [InspectorSignUpLocalEntity.mailingAddress].
  static final mailingAddress =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[15],
      );

  /// See [InspectorSignUpLocalEntity.uploadedIdOrLicenseDocument].
  static final uploadedIdOrLicenseDocument =
      obx.QueryRelationToOne<InspectorSignUpLocalEntity, UserDocumentEntity>(
        _entities[4].properties[16],
      );

  /// See [InspectorSignUpLocalEntity.uploadedCoiDocument].
  static final uploadedCoiDocument =
      obx.QueryRelationToOne<InspectorSignUpLocalEntity, UserDocumentEntity>(
        _entities[4].properties[17],
      );

  /// See [InspectorSignUpLocalEntity.workHistoryDescription].
  static final workHistoryDescription =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[18],
      );

  /// See [InspectorSignUpLocalEntity.referenceDocuments].
  static final referenceDocuments =
      obx.QueryStringVectorProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[19],
      );

  /// See [InspectorSignUpLocalEntity.profileImage].
  static final profileImage =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[20],
      );

  /// See [InspectorSignUpLocalEntity.agreedToTerms].
  static final agreedToTerms =
      obx.QueryBooleanProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[21],
      );

  /// See [InspectorSignUpLocalEntity.isTruthfully].
  static final isTruthfully =
      obx.QueryBooleanProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[22],
      );

  /// See [InspectorSignUpLocalEntity.role].
  static final role = obx.QueryIntegerProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[23],
  );

  /// See [InspectorSignUpLocalEntity.deviceType].
  static final deviceType = obx.QueryStringProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[24],
  );

  /// See [InspectorSignUpLocalEntity.deviceToken].
  static final deviceToken =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[25],
      );

  /// See [InspectorSignUpLocalEntity.locationType].
  static final locationType =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[26],
      );

  /// See [InspectorSignUpLocalEntity.locationName].
  static final locationName =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[27],
      );

  /// See [InspectorSignUpLocalEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[28],
  );

  /// See [InspectorSignUpLocalEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<InspectorSignUpLocalEntity>(
    _entities[4].properties[29],
  );

  /// See [InspectorSignUpLocalEntity.coiExpiryDate].
  static final coiExpiryDate =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[30],
      );

  /// See [InspectorSignUpLocalEntity.documentExpiryDate].
  static final documentExpiryDate =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[31],
      );

  /// See [InspectorSignUpLocalEntity.documentTypeId].
  static final documentTypeId =
      obx.QueryStringProperty<InspectorSignUpLocalEntity>(
        _entities[4].properties[32],
      );

  /// see [InspectorSignUpLocalEntity.serviceAreas]
  static final serviceAreas =
      obx.QueryBacklinkToMany<
        ServiceAreaLocalEntity,
        InspectorSignUpLocalEntity
      >(ServiceAreaLocalEntity_.inspector);

  /// see [InspectorSignUpLocalEntity.iccDocuments]
  static final iccDocuments =
      obx.QueryBacklinkToMany<
        IccDocumentLocalEntity,
        InspectorSignUpLocalEntity
      >(IccDocumentLocalEntity_.inspector);
}

/// [UserDocumentEntity] entity fields to define ObjectBox queries.
class UserDocumentEntity_ {
  /// See [UserDocumentEntity.id].
  static final id = obx.QueryIntegerProperty<UserDocumentEntity>(
    _entities[5].properties[0],
  );

  /// See [UserDocumentEntity.documentUrl].
  static final documentUrl = obx.QueryStringProperty<UserDocumentEntity>(
    _entities[5].properties[1],
  );

  /// See [UserDocumentEntity.fileName].
  static final fileName = obx.QueryStringProperty<UserDocumentEntity>(
    _entities[5].properties[2],
  );

  /// See [UserDocumentEntity.inspector].
  static final inspector =
      obx.QueryRelationToOne<UserDocumentEntity, InspectorSignUpLocalEntity>(
        _entities[5].properties[3],
      );
}
